# Generated by Django 5.0.4 on 2024-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=b'I01\n', max_length=250, null=b'I01\n')),
                ('photo_book', models.ImageField(blank=True, null=b'I01\n', upload_to='photos')),
                ('photo_author', models.ImageField(blank=True, null=b'I01\n', upload_to='photos')),
                ('pages', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('price', models.DecimalField(blank=b'I01\n', decimal_places=2, max_digits=5, null=b'I01\n')),
                ('rental_price_day', models.DecimalField(blank=b'I01\n', decimal_places=2, max_digits=5, null=b'I01\n')),
                ('rental_period', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=b'I01\n', choices=[('avaliable', 'avaliable'), ('rental', 'rental'), ('sold', 'sold')], max_length=50, null=b'I01\n')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
