# Generated by Django 5.0.4 on 2024-04-25 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=b'I01\n', null=b'I01\n', on_delete=django.db.models.deletion.PROTECT, to='lms_app.category'),
            preserve_default=b'I01\n',
        ),
    ]
