# Generated by Django 5.0.4 on 2024-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental',
            field=models.DecimalField(blank=b'I01\n', decimal_places=2, max_digits=5, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
